use aarch suffix so dockerfile can be reused

diff --git a/swift-ci/main/amazon-linux/2023/Verification/6.2/Dockerfile b/swift-ci/main/amazon-linux/2023/Verification/6.2/Dockerfile
--- a/swift-ci/main/amazon-linux/2023/Verification/6.2/Dockerfile
+++ b/swift-ci/main/amazon-linux/2023/Verification/6.2/Dockerfile
@@ -51,7 +51,19 @@ ENV SWIFT_PLATFORM=$SWIFT_PLATFORM \
     SWIFT_WEBROOT=$SWIFT_WEBROOT \
     SWIFT_PREFIX=$SWIFT_PREFIX
 
-RUN SWIFT_BIN_URL="$SWIFT_WEBROOT/tmp-ci-nightly/development/swift-6.2-bootstrap/amazonlinux2023/latest.tar.gz" \
+RUN set -e; \
+    ARCH_NAME="$(rpm --eval '%{_arch}')"; \
+    url=; \
+    case "${ARCH_NAME##*-}" in \
+        'x86_64') \
+            OS_ARCH_SUFFIX=''; \
+            ;; \
+        'aarch64') \
+            OS_ARCH_SUFFIX='-aarch64'; \
+            ;; \
+        *) echo >&2 "error: unsupported architecture: '$ARCH_NAME'"; exit 1 ;; \
+    esac; \
+    SWIFT_BIN_URL="$SWIFT_WEBROOT/tmp-ci-nightly/development/swift-6.2-bootstrap/amazonlinux2023$OS_ARCH_SUFFIX/latest.tar.gz" \
     && curl -fsSL "$SWIFT_BIN_URL" -o swift.tar.gz \
     && mkdir -p $SWIFT_PREFIX \
     && tar -xzf swift.tar.gz --directory $SWIFT_PREFIX \
diff --git a/swift-ci/main/ubuntu/24.04/Verification/6.2/Dockerfile b/swift-ci/main/ubuntu/24.04/Verification/6.2/Dockerfile
--- a/swift-ci/main/ubuntu/24.04/Verification/6.2/Dockerfile
+++ b/swift-ci/main/ubuntu/24.04/Verification/6.2/Dockerfile
@@ -48,7 +48,19 @@ ENV SWIFT_PLATFORM=$SWIFT_PLATFORM \
     SWIFT_WEBROOT=$SWIFT_WEBROOT \
     SWIFT_PREFIX=$SWIFT_PREFIX
 
-RUN SWIFT_BIN_URL="$SWIFT_WEBROOT/tmp-ci-nightly/development/swift-6.2-bootstrap/ubuntu2404/latest.tar.gz" \
+RUN set -e; \
+    ARCH_NAME="$(dpkg --print-architecture)"; \
+    url=; \
+    case "${ARCH_NAME##*-}" in \
+        'amd64') \
+            OS_ARCH_SUFFIX=''; \
+            ;; \
+        'arm64') \
+            OS_ARCH_SUFFIX='-aarch64'; \
+            ;; \
+        *) echo >&2 "error: unsupported architecture: '$ARCH_NAME'"; exit 1 ;; \
+    esac; \
+    SWIFT_BIN_URL="$SWIFT_WEBROOT/tmp-ci-nightly/development/swift-6.2-bootstrap/ubuntu2404$OS_ARCH_SUFFIX/latest.tar.gz" \
     && export DEBIAN_FRONTEND=noninteractive \
     && apt-get -q update && apt-get -q install -y curl && rm -rf /var/lib/apt/lists/* \
     && curl -fsSL "$SWIFT_BIN_URL" -o swift.tar.gz \
