Add sccache to swift-ci/main Linux Dockerfiles
Installs a pinned sccache v0.17.0 musl-static binary to /usr/local/bin
across all Linux build images so builds can opt into compiler caching.

diff --git a/swift-ci/main/debian/9/Dockerfile b/swift-ci/main/debian/9/Dockerfile
--- a/swift-ci/main/debian/9/Dockerfile
+++ b/swift-ci/main/debian/9/Dockerfile
@@ -15,8 +15,10 @@ RUN apt-get update
 
 RUN apt-get --no-install-recommends -y install \
   build-essential       \
+  ca-certificates       \
   clang                 \
   cmake                 \
+  curl                  \
   git                   \
   icu-devtools          \
   libcurl4-openssl-dev  \
@@ -37,11 +39,23 @@ RUN apt-get --no-install-recommends -y install \
   systemtap-sdt-dev     \
   tzdata                \
   unzip                 \
-  ca-certificates       \
   uuid-dev
 
 COPY swift-ci/dependencies/requirements.txt /dependencies/
 RUN pip3 install -r /dependencies/requirements.txt
+
+ARG SCCACHE_VERSION=v0.17.0
+RUN set -e; \
+    ARCH_NAME="$(dpkg --print-architecture)"; \
+    case "$ARCH_NAME" in \
+        'amd64') SCCACHE_ARCH='x86_64' ;; \
+        'arm64') SCCACHE_ARCH='aarch64' ;; \
+        *) echo >&2 "error: unsupported architecture: '$ARCH_NAME'"; exit 1 ;; \
+    esac; \
+    curl -fsSL "https://github.com/mozilla/sccache/releases/download/${SCCACHE_VERSION}/sccache-${SCCACHE_VERSION}-${SCCACHE_ARCH}-unknown-linux-musl.tar.gz" -o sccache.tar.gz \
+    && tar -xzf sccache.tar.gz \
+    && install -m 755 "sccache-${SCCACHE_VERSION}-${SCCACHE_ARCH}-unknown-linux-musl/sccache" /usr/local/bin/sccache \
+    && rm -rf sccache.tar.gz "sccache-${SCCACHE_VERSION}-${SCCACHE_ARCH}-unknown-linux-musl"
 
 USER build-user
 
diff --git a/swift-ci/main/ubuntu/24.04/Bootstrap/Dockerfile b/swift-ci/main/ubuntu/24.04/Bootstrap/Dockerfile
--- a/swift-ci/main/ubuntu/24.04/Bootstrap/Dockerfile
+++ b/swift-ci/main/ubuntu/24.04/Bootstrap/Dockerfile
@@ -12,6 +12,7 @@ RUN apt-get -y update && apt-get -y install \
   build-essential       \
   clang                 \
   cmake                 \
+  curl                  \
   git                   \
   icu-devtools          \
   libc++-18-dev         \
@@ -39,6 +40,19 @@ RUN apt-get -y update && apt-get -y install \
 
 COPY swift-ci/dependencies/requirements.txt /dependencies/
 RUN pip3 install -r /dependencies/requirements.txt --break-system-packages
+
+ARG SCCACHE_VERSION=v0.17.0
+RUN set -e; \
+    ARCH_NAME="$(dpkg --print-architecture)"; \
+    case "$ARCH_NAME" in \
+        'amd64') SCCACHE_ARCH='x86_64' ;; \
+        'arm64') SCCACHE_ARCH='aarch64' ;; \
+        *) echo >&2 "error: unsupported architecture: '$ARCH_NAME'"; exit 1 ;; \
+    esac; \
+    curl -fsSL "https://github.com/mozilla/sccache/releases/download/${SCCACHE_VERSION}/sccache-${SCCACHE_VERSION}-${SCCACHE_ARCH}-unknown-linux-musl.tar.gz" -o sccache.tar.gz \
+    && tar -xzf sccache.tar.gz \
+    && install -m 755 "sccache-${SCCACHE_VERSION}-${SCCACHE_ARCH}-unknown-linux-musl/sccache" /usr/local/bin/sccache \
+    && rm -rf sccache.tar.gz "sccache-${SCCACHE_VERSION}-${SCCACHE_ARCH}-unknown-linux-musl"
 
 USER build-user
 WORKDIR /home/build-user
